# foodcom
# best!
#loss_kd: 0.7
#loss_health: 0.05

#kd_threshold: 0.16
#loss_kd: 0.4
#loss_health: 0.05
#reg_weight: 0.1
#learner: adam
#learning_rate: 0.001
#train_batch_size: 512
#epochs: 100
#eval_step: 10
#ui_layers: 2

# allrecipe
#loss_kd: [0, 0.0001, 0.001, 0.01, 0.1]
#loss_health: [0, 0.001, 0.01, 0.1, 1]

#loss_health: [0, 0.01, 0.05, 0.1, 0.5]
#loss_health: [0.001, 0.005, 1]
# best!!!
#loss_kd: 0.0001
#loss_health: 0.1

kd_threshold: 0.4
loss_kd: 0.05
loss_health: 0.1
reg_weight: 0.5
learner: adam
learning_rate: 0.002
train_batch_size: 512
epochs: 50
eval_step: 10
learning_rate_scheduler: [0.5, 50]
ui_layers: 1

n_layers: 2                   # (int) The number of layers in LightGCN.
embedding_size: 64              # (int) The embedding size of users and items.
num_hidden_layers: 2
num_attention_heads: 2
attention_probs_dropout_prob: 0.5
hidden_act: gelu

load_RecipeIngre_graph: True
use_health_level_multi_hot: True
graph_inference_fast: True
small_ingre: True

seed: [999]
#flag: [0]
## 0 no G*
#hyper_parameters: ["seed"]

