# grid search
# learning_rate: [0.001, 0.005, 0.0001, 0.0005]
# hyper_parameters: ["learning_rate"]

# Foodcom & Allrecipes

embedding_size: 64
num_hidden_layers: 2
num_attention_heads: 2
inner_size: 256
attention_probs_dropout_prob: 0.5
hidden_dropout_prob: 0.5
hidden_act: gelu
in_channel: [64, 32]
out_channel: [32, 64]

learner: adam
learning_rate: 0.0005
epochs: 100
eval_step: 10
train_batch_size: 512

load_UserRecipe_graph: True
load_RecipeIngre_graph: True
load_RecipeCalories_graph: True
use_cal_level: True
seed: [999]

regs: 0.01
reg_image: 1
reg_w: 0.05
reg_g: 0.01
reg_health: 0.01
ssl: 0.008
SCHGN_ssl: True

#hyper_parameters: ["regs"]
